src/Lib/Diagnostics/Minecraft/Animation.ts
=> Removing setting to false as it overrides found true

src/Lib/Diagnostics/BehaviorPack/Block/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Block/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Block/entry.ts
=> Add block component errors

src/Lib/Diagnostics/BehaviorPack/Block/components/diagnose.ts
=> - Fix block filter

src/Lib/Diagnostics/BehaviorPack/Entity/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Item/components/diagnose.ts
This syntax
```json
minecraft:cow<minecraft:entity_spawned>
```
=> Allow entity events in item component checks

src/Lib/Diagnostics/BehaviorPack/Entity/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Item/components/diagnose.ts, src/Lib/Diagnostics/Minecraft/Animation.ts
Resolve #204
Resolve #210 too, same issue but I understood it wrong hence the inaccurate title
=> Check vanilla controllers to see if animations are used

src/Lib/Diagnostics/BehaviorPack/Entity/properties.ts
Needs #267 to be fixed before it can be merged.
=> Stricter entity property checking for floats and integers

src/Lib/Diagnostics/BehaviorPack/Block/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Item/components/diagnose.ts
Resolves https://github.com/Blockception/VSCode-Bedrock-Development-Extension/issues/692
=> Account for block references being objects of format {"name": "value"}

src/Lib/Diagnostics/Minecraft/Language.ts
=> Remove \n error

src/Lib/Diagnostics/BehaviorPack/Block/components/dependencies.ts, src/Lib/Diagnostics/BehaviorPack/Block/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Block/entry.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/dependencies.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/loot.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/trade.ts, src/Lib/Diagnostics/BehaviorPack/Entity/entry.ts, src/Lib/Diagnostics/BehaviorPack/Item/components/dependencies.ts, src/Lib/Diagnostics/BehaviorPack/Item/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Item/entry.ts, src/Lib/utility/components/checks.ts, src/Lib/utility/components/components.ts
Need to have source definitions available for components checks
=> feat: adding source item for components in the context object

src/Lib/Diagnostics/Format/diagnose.ts
=> Include check for volume deprecation

src/Lib/Diagnostics/Minecraft/Manifest.ts
=> Check if manifest matches semver

src/Lib/Diagnostics/ResourcePack/Entity/entry.ts
=> Add check for spawn_egg.texture

src/Lib/Diagnostics/BehaviorPack/Animation Controllers/entry.ts, src/Lib/Diagnostics/BehaviorPack/Animation/entry.ts, src/Lib/Diagnostics/BehaviorPack/Block/entry.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Entity/entry.ts, src/Lib/Diagnostics/BehaviorPack/Entity/events.ts, src/Lib/Diagnostics/BehaviorPack/Item/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Item/entry.ts, src/Lib/Diagnostics/Minecraft/Animation Controllers.ts, src/Lib/Diagnostics/Minecraft/Animation.ts, src/Lib/Diagnostics/Minecraft/Filter/Filters/property.ts, src/Lib/Diagnostics/ResourcePack/anim or controller.ts, src/Lib/utility/components/checks.ts
Some of these are in preparation for 1.21.70
=> A lot of miscellaneous tweaks for 1.21.70

src/Lib/Diagnostics/BehaviorPack/Block/entry.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Entity/entry.ts, src/Lib/Diagnostics/BehaviorPack/Entity/events.ts, src/Lib/Diagnostics/BehaviorPack/Entity/properties.ts, src/Lib/Diagnostics/BehaviorPack/Item/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Item/entry.ts, src/Lib/Diagnostics/ResourcePack/Block/entry.ts, src/Lib/Diagnostics/ResourcePack/Particle/entry.ts, src/Lib/Diagnostics/ResourcePack/Sounds/diagnostics.ts, src/Lib/Diagnostics/ResourcePack/Texture Atlas/entry.ts
Resolve #315 
Resolve #237 
Resolve #233 
Resolve #173
=> More misc improvements

src/Lib/Diagnostics/BehaviorPack/Entity/events.ts
If you could get this merged & released that'd be great
=> Fix trigger check for sequence & randomize events

src/Lib/Diagnostics/BehaviorPack/Entity/components/dependencies.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/diagnose.ts
=> Added more entity component checking

eslint.config.mjs, src/Lib/Diagnostics/BehaviorPack/Animation Controllers/diagnostics.ts, src/Lib/Diagnostics/BehaviorPack/BehaviorPack.ts, src/Lib/Diagnostics/BehaviorPack/Block/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Block/entry.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/dependencies.ts, src/Lib/Diagnostics/BehaviorPack/Entity/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Entity/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Entity/events.ts, src/Lib/Diagnostics/BehaviorPack/Entity/properties.ts, src/Lib/Diagnostics/BehaviorPack/Feature/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Feature/entry.ts, src/Lib/Diagnostics/BehaviorPack/Feature/index.ts, src/Lib/Diagnostics/BehaviorPack/Item/components/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Item/diagnose.ts, src/Lib/Diagnostics/BehaviorPack/Item/entry.ts, src/Lib/Diagnostics/BehaviorPack/Mcfunction/commands.ts, src/Lib/Diagnostics/BehaviorPack/Structure/diagnose.ts, src/Lib/Diagnostics/Minecraft/Filter/Filters/has_equipment.ts, src/Lib/Diagnostics/Minecraft/Filter/Filters/property.ts, src/Lib/Diagnostics/Minecraft/Filter/diagnose.ts, src/Lib/Diagnostics/Minecraft/Language.ts, src/Lib/Diagnostics/ResourcePack/Block/entry.ts, src/Lib/Diagnostics/ResourcePack/Texture Atlas/entry.ts, src/Lib/Types/Diagnoser.ts
(I should really split these into separate PRs in the future, shouldn't I?)
Resolve #1 
Resolve #43 
Resolve #44 
Resolve #166 
Resolve #167 
Resolve #171 
Resolve #349
=> A lot of random updates

package-lock.json, package.json, test/diagnoser.ts, test/files-test/files.test.ts, test/files-test/test-bp/animation_controllers/controller.npc.json, test/files-test/test-bp/animations/animation.item.json, test/files-test/test-bp/entities/sample.json, test/files-test/test-bp/functions/test.mcfunction, test/files-test/test-bp/items/apple.json, test/files-test/test-bp/manifest.json, test/files-test/test-rp/entity/sample.entity.json, test/files-test/test-rp/manifest.json, test/files-test/test-rp/render_controllers/sample.render_controllers.json
Adding tests where you can add files, these tests just ensure nothing crashes
=> adding files tests to ensure no exceptions are thrown

package-lock.json, src/lib/diagnostics/behavior-pack/behavior-pack.ts, src/lib/diagnostics/behavior-pack/feature-rule/diagnose.ts, src/lib/diagnostics/behavior-pack/feature-rule/entry.ts, src/lib/diagnostics/behavior-pack/feature-rule/index.ts
You'll notice for both this and the feature validation, I've left the vanilla part commented out.
Hoping for https://github.com/Blockception/BC-Minecraft-Bedrock-Vanilla-Data/issues/13 and for vanilla feature rule ids so that it can be added in
=> Added feature rule checking

src/lib/diagnostics/resource-pack/particle/components/diagnose.ts
=> Changed radius -> collision_radius in particle check

src/lib/diagnostics/behavior-pack/recipe/entry.ts
=> Added blast_furance tag to allowable list of tags

package-lock.json, package.json, src/lib/diagnostics/behavior-pack/behavior-pack.ts, src/lib/diagnostics/behavior-pack/biome/components/dependencies.ts, src/lib/diagnostics/behavior-pack/biome/components/diagnose.ts, src/lib/diagnostics/behavior-pack/biome/components/index.ts, src/lib/diagnostics/behavior-pack/biome/diagnose.ts, src/lib/diagnostics/behavior-pack/biome/document.ts, src/lib/diagnostics/behavior-pack/biome/index.ts, src/lib/diagnostics/behavior-pack/block/components/diagnose.ts, src/lib/diagnostics/behavior-pack/entity/components/diagnose.ts, src/lib/diagnostics/behavior-pack/feature-rule/document.ts, src/lib/diagnostics/behavior-pack/item/__snapshots__/diagnose.test.ts.snap, src/lib/diagnostics/behavior-pack/item/diagnose.test.ts, src/lib/diagnostics/behavior-pack/item/diagnose.ts, src/lib/diagnostics/minecraft/filter/diagnose.ts, src/lib/diagnostics/minecraft/filter/filters/has_biome_tag.ts, src/lib/diagnostics/packs/duplicate-check.ts
Noticed issues with the molang parsing; reported all of them
=> 1.21.110 + Misc
